/** Phrases and tokens that mark shock, urgency, ads, or sentiment padding. */

export const BAIT_PHRASES = [
  "you won't believe",
  "you will not believe",
  "you wont believe",
  "what happened next",
  "this changes everything",
  "goes viral",
  "went viral",
  "breaking:",
  "breaking news",
  "must-see",
  "must see",
  "must-read",
  "must read",
  "unbelievable",
  "insane",
  "mind-blowing",
  "mind blowing",
  "jaw-dropping",
  "jaw dropping",
  "slammed",
  "rips",
  "destroys",
  "destroyed",
  "obliterates",
  "crushes",
  "explodes",
  "exploded",
  "erupts",
  "erupted",
  "just dropped",
  "melts down",
  "meltdown",
  "furious",
  "hate this",
  "nightmare",
  "terrifying",
  "you should be terrified",
  "panic",
  "chaos",
  "outrage",
  "outraged",
  "furious",
  "slams",
  "brutal",
  "shocking",
  "shocked the world",
  "shocks the world",
  "in shambles",
  "it's over",
  "its over",
  "game over",
  "everyone is talking",
  "the internet is",
  "ratioed",
  "let that sink in",
  "thread 🧵",
  "a thread",
  "drop a like",
  "like and subscribe",
  "smash that",
  "link in bio",
  "swipe up",
];

export const AD_PHRASES = [
  "sponsored",
  "paid partnership",
  "paid promotion",
  "affiliate",
  "shop now",
  "buy now",
  "order now",
  "limited time",
  "use code",
  "promo code",
  "discount code",
  "free shipping",
  "act now",
  "don't miss",
  "dont miss",
  "hurry",
  "only a few left",
  "click here",
  "tap to buy",
  "subscribe for",
  "sign up now",
  "download the app",
  "install now",
  "this post is sponsored",
  "#ad",
  "#sponsored",
  "partnered with",
];

export const SENTIMENT_PADDING = [
  "so proud of",
  "can't even",
  "cant even",
  "i'm screaming",
  "im screaming",
  "crying",
  "literally shaking",
  "love this so much",
  "hate this so much",
  "best day ever",
  "worst day ever",
  "my heart is full",
  "sending love",
  "prayers",
  "blessed",
  "unhinged",
  "iconic",
  "slay",
  "ate and left",
];

export const ENGAGEMENT_PHRASES = [
  "likes",
  "like count",
  "retweets",
  "reposts",
  "quote tweets",
  "comments",
  "ratio",
  "impressions",
  "views",
  "going viral",
  "for you page",
  "fyp",
  "algorithm",
];

export const ACRONYMS = new Set([
  "AI",
  "API",
  "CPU",
  "GPU",
  "NASA",
  "FDA",
  "WHO",
  "UN",
  "EU",
  "UK",
  "US",
  "USA",
  "CEO",
  "CFO",
  "CTO",
  "IMF",
  "GDP",
  "ETF",
  "IPO",
  "EV",
  "VR",
  "AR",
  "LLM",
  "RSS",
  "HTTP",
  "HTML",
  "CSS",
  "SQL",
  "PDF",
  "USB",
  "AMD",
  "ARM",
  "IBM",
  "AWS",
  "GCP",
  "BBC",
  "CNN",
  "NYT",
  "WSJ",
  "NPR",
  "AP",
  "NATO",
  "OPEC",
]);

export const ALL_DROP_PHRASES = [
  ...BAIT_PHRASES,
  ...AD_PHRASES,
  ...SENTIMENT_PADDING,
];
